name: Deployment
on:
  release:
    types: [created]

jobs:
  build-docker-images:
    uses: ./.github/workflows/docker-build-image.yml
    secrets:
      PUBLISH_TO_GITHUB_REPO_TOKEN: ${{ secrets.PUBLISH_TO_GITHUB_REPO_TOKEN }}
      REGISTRY_PASSWORD_DOCKER: ${{ secrets.REGISTRY_PASSWORD_DOCKER }}
    with:
      push-images: true
